[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -I../common
  -Iinclude
build_src_filter =
  +<*>
  +<../common/**>
lib_deps =
  PubSubClient @ ^2.8
  ArduinoJson @ ^7.2.1
