[platformio]
default_envs = nanoesp32c6-n16

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared-libs

build_flags =
  -I ../common
  -D MOT_GPS_BAUD=9600

lib_deps =
  Update
  HTTPClient
  mikalhart/TinyGPSPlus @ ^1.0.3
  bblanchon/ArduinoJson @ ^7.4.3
  PubSubClient @ ^2.8

[env:nanoesp32c6-n16]
board = esp32-c6-devkitc-1
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = partitions_16mb.csv
build_flags =
  ${env.build_flags}
  -D MOT_BOARD=\"nanoESP32-C6-N16\"
  -D MOT_CAN1_RX_PIN=0
  -D MOT_CAN1_TX_PIN=1
  -D MOT_CAN2_RX_PIN=2
  -D MOT_CAN2_TX_PIN=3
  -D MOT_GPS_RX_PIN=20
  -D MOT_GPS_TX_PIN=21

[env:xiao-esp32c6]
board = seeed_xiao_esp32c6
board_build.partitions = partitions_4mb.csv
build_flags =
  ${env.build_flags}
  -D MOT_BOARD=\"Seeed-XIAO-ESP32-C6\"
  -D MOT_CAN1_RX_PIN=0
  -D MOT_CAN1_TX_PIN=1
  -D MOT_CAN2_RX_PIN=2
  -D MOT_CAN2_TX_PIN=21
  -D MOT_GPS_RX_PIN=17
  -D MOT_GPS_TX_PIN=16
  -D MOT_XIAO_BOARD=1

[env:nanoesp32c6-n16-aws]
extends = env:nanoesp32c6-n16
board_build.filesystem = littlefs
build_flags =
  ${env:nanoesp32c6-n16.build_flags}
  -D MOT_AWS_IOT=1

[env:xiao-esp32c6-aws]
extends = env:xiao-esp32c6
board_build.filesystem = littlefs
build_flags =
  ${env:xiao-esp32c6.build_flags}
  -D MOT_AWS_IOT=1
