#include "lilygo_web.h"
#include <WebServer.h>
#include <WiFi.h>
#include <Update.h>
#include "board_config.h"
#include "config/lilygo_config.h"
#include "modem/lilygo_modem.h"
#include "network/lilygo_network.h"
#include "gps/l76k_gps.h"
static WebServer server(80); static bool rebootPending=false; static unsigned long rebootAtMs=0;
static String pageHeader(const char* title){String s; s+="<!doctype html><html><head><meta charset='utf-8'>";s+="<meta name='viewport' content='width=device-width,initial-scale=1'>";s+="<title>";s+=title;s+="</title>";s+="<style>body{font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Arial,sans-serif;margin:24px;max-width:1000px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;margin:12px 0}pre{background:#111;color:#eee;border-radius:8px;padding:12px;overflow:auto;white-space:pre-wrap}.muted{color:#666}button{padding:10px 16px;border-radius:8px;border:1px solid #999;background:#f5f5f5;margin:4px}input{padding:9px;width:100%;box-sizing:border-box;margin:6px 0 10px}label{font-weight:600}</style></head><body>";return s;}
static void handleRoot(){String s=pageHeader("MOT LilyGO");s+="<h1>Microlino Open Telemetry</h1><p class='muted'>";s+=MOT_VERSION;s+=" · ";s+=MOT_BOARD;s+=" · ";s+=lilygoDeviceName();s+="</p><p><a href='/config'>Config</a> · <a href='/ota'>OTA</a> · <a href='/api/status'>Status JSON</a></p>";s+="<div class='card'><h2>Network</h2><button onclick='loadNetwork()'>Refresh</button><pre id='network'>Loading...</pre></div>";s+="<div class='card'><h2>LTE Modem</h2><button onclick='loadModem()'>Refresh</button><pre id='modem'>Loading...</pre></div>";s+="<div class='card'><h2>L76K GPS</h2><button onclick='loadGps()'>Refresh</button><pre id='gps'>Loading...</pre></div>";s+="<script>async function loadNetwork(){const r=await fetch('/api/lilygo/network');document.getElementById('network').textContent=JSON.stringify(await r.json(),null,2)}async function loadModem(){const r=await fetch('/api/lilygo/modem');document.getElementById('modem').textContent=JSON.stringify(await r.json(),null,2)}async function loadGps(){const r=await fetch('/api/lilygo/gps');document.getElementById('gps').textContent=JSON.stringify(await r.json(),null,2)}loadNetwork();loadModem();loadGps();setInterval(loadNetwork,5000);setInterval(loadGps,3000);</script></body></html>";server.send(200,"text/html",s);}
static void handleConfig(){String s=pageHeader("MOT LilyGO Config");s+="<h1>Configuration</h1><form method='POST' action='/config/save'>";s+="<label>Device name</label><input name='deviceName' value='"+lilygoDeviceName()+"'>";s+="<label>Vehicle ID</label><input name='vehicleId' value='"+config.vehicleId+"'>";s+="<label>MQTT Prefix</label><input name='mqttPrefix' value='"+config.mqttPrefix+"'>";s+="<label>WiFi SSID</label><input name='wifiSsid' value='"+config.wifiSsid+"'>";s+="<label>WiFi Password</label><input name='wifiPass' type='password' value='"+config.wifiPass+"'>";s+="<label>LTE APN</label><input name='lteApn' value='"+config.lteApn+"'>";s+="<label>MQTT Host</label><input name='mqttHost' value='"+config.mqttHost+"'>";s+="<label>MQTT Port</label><input name='mqttPort' value='"+String(config.mqttPort)+"'>";s+="<label>MQTT User</label><input name='mqttUser' value='"+config.mqttUser+"'>";s+="<label>MQTT Password</label><input name='mqttPass' type='password' value='"+config.mqttPass+"'>";s+="<label>OTA Password</label><input name='otaPassword' type='password' value='"+config.otaPassword+"'><button type='submit'>Save & reboot</button></form>";s+="<div class='card'><h2>Export</h2><p><a href='/api/config/export'>Download config JSON</a></p></div>";s+="<div class='card'><h2>Factory Reset</h2><form method='POST' action='/factory-reset' onsubmit=\"return confirm('Factory Reset wirklich ausführen? Alle Einstellungen werden gelöscht.');\"><button type='submit'>Clear config & reboot</button></form></div><p><a href='/'>Back</a></p></body></html>";server.send(200,"text/html",s);}
static void handleConfigSave(){config.deviceName=server.arg("deviceName");config.vehicleId=server.arg("vehicleId");config.mqttPrefix=server.arg("mqttPrefix");config.wifiSsid=server.arg("wifiSsid");config.wifiPass=server.arg("wifiPass");config.lteApn=server.arg("lteApn");config.mqttHost=server.arg("mqttHost");config.mqttPort=(uint16_t)server.arg("mqttPort").toInt();if(config.mqttPort==0)config.mqttPort=1883;config.mqttUser=server.arg("mqttUser");config.mqttPass=server.arg("mqttPass");config.otaPassword=server.arg("otaPassword");saveLilygoConfig();server.send(200,"text/html","<p>Saved. Rebooting...</p>");rebootPending=true;rebootAtMs=millis()+1000;}
static void handleFactoryReset(){clearLilygoConfig();server.send(200,"text/html","<p>Config cleared. Rebooting...</p>");rebootPending=true;rebootAtMs=millis()+1000;} static void handleConfigExport(){server.sendHeader("Content-Disposition","attachment; filename=mot-lilygo-config.json");server.send(200,"application/json",lilygoConfigJson(true));}
static void handleStatusJson(){String json="{";json+="\"firmware\":\"" MOT_VERSION "\",";json+="\"board\":\"" MOT_BOARD "\",";json+="\"deviceName\":\""+lilygoDeviceName()+"\",";json+="\"network\":"+lilygoNetworkStatusJson()+",";json+="\"modem\":"+lilygoModemStatusJson()+",";json+="\"gps\":"+l76kGpsStatusJson();json+="}";server.send(200,"application/json",json);} static void handleModem(){server.send(200,"application/json",lilygoModemStatusJson());} static void handleNetwork(){server.send(200,"application/json",lilygoNetworkStatusJson());} static void handleGps(){server.send(200,"application/json",l76kGpsStatusJson());}
static bool otaAllowed(){String pass=config.otaPassword;pass.trim();if(pass.isEmpty())return true;return server.hasArg("password")&&server.arg("password")==pass;} static void handleOtaPage(){String s=pageHeader("MOT LilyGO OTA");s+="<h1>OTA Update</h1><form method='POST' action='/ota/update' enctype='multipart/form-data'><label>Password</label><input name='password' type='password'><input type='file' name='firmware'><button type='submit'>Upload firmware</button></form><p><a href='/'>Back</a></p></body></html>";server.send(200,"text/html",s);} static void handleOtaDone(){if(!otaAllowed()){server.send(403,"text/plain","OTA not allowed");return;}bool ok=!Update.hasError();server.send(ok?200:500,"text/plain",ok?"OTA OK. Rebooting.":"OTA failed.");if(ok){rebootPending=true;rebootAtMs=millis()+1000;}} static void handleOtaUpload(){if(!otaAllowed())return;HTTPUpload& upload=server.upload();if(upload.status==UPLOAD_FILE_START)Update.begin(UPDATE_SIZE_UNKNOWN);else if(upload.status==UPLOAD_FILE_WRITE)Update.write(upload.buf,upload.currentSize);else if(upload.status==UPLOAD_FILE_END)Update.end(true);}
void setupLilygoWeb(){server.on("/",HTTP_GET,handleRoot);server.on("/config",HTTP_GET,handleConfig);server.on("/config/save",HTTP_POST,handleConfigSave);server.on("/factory-reset",HTTP_POST,handleFactoryReset);server.on("/api/config/export",HTTP_GET,handleConfigExport);server.on("/api/status",HTTP_GET,handleStatusJson);server.on("/api/lilygo/network",HTTP_GET,handleNetwork);server.on("/api/lilygo/modem",HTTP_GET,handleModem);server.on("/api/lilygo/gps",HTTP_GET,handleGps);server.on("/api/lilygo/gnss",HTTP_GET,handleGps);server.on("/ota",HTTP_GET,handleOtaPage);server.on("/ota/update",HTTP_POST,handleOtaDone,handleOtaUpload);server.begin();Serial.println("LilyGO Web UI started");} void lilygoWebLoop(){server.handleClient();if(rebootPending&&millis()>rebootAtMs)ESP.restart();}
