[env:lilygo-t-a7670]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags =
  -D MOT_BOARD_LILYGO_T_A7670=1
  -D LILYGO_T_A7670
  -D LILYGO_GPS_SHIELD
  -I include
  ; Optional WiFi-first fallback:
  ; -D WIFI_SSID=\"YOUR_WIFI\"
  ; -D WIFI_PASS=\"YOUR_PASSWORD\"

lib_deps =
  ArduinoJson @ ^7.4.3
  mikalhart/TinyGPSPlus @ ^1.0.3
