[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared-libs

build_flags =
  -D CAN_RX_PIN=27
  -D CAN_TX_PIN=26
  -I src/common
  -I include

build_src_filter =
  +<*>
  -<gps/gps_test_main.cpp>
  +<common/**>

lib_deps =
  mikalhart/TinyGPSPlus @ ^1.0.3
  PubSubClient @ ^2.8
  ArduinoJson @ ^7.4.3


[env:esp32dev-aws]
extends = env:esp32dev
board_build.filesystem = littlefs
build_flags =
  ${env:esp32dev.build_flags}
  -D MOT_AWS_IOT=1


[env:esp32dev-gps-test]
extends = env:esp32dev
build_src_filter =
  -<*>
  +<gps/gps_test_main.cpp>
build_flags =
  -D MOT_GPS_RX_PIN=16
  -D MOT_GPS_TX_PIN=17
  -D MOT_GPS_BAUD=9600
