#include "lilygo_network.h"
#include <WiFi.h>
#include "board_config.h"
#include "config/lilygo_config.h"
#include "modem/lilygo_modem.h"
static LilygoNetworkMode mode=LilygoNetworkMode::AP_ONLY; static String apSsid; static unsigned long lastCheckMs=0;
static String chipId(){uint64_t mac=ESP.getEfuseMac();char buf[16];snprintf(buf,sizeof(buf),"%06X",(uint32_t)(mac&0xFFFFFF));return String(buf);} static void startAp(){apSsid=String(SETUP_AP_SSID)+"-"+chipId();WiFi.mode(WIFI_AP);WiFi.softAP(apSsid.c_str(),SETUP_AP_PASS);Serial.printf("Setup AP: %s\n",apSsid.c_str());Serial.printf("Setup AP IP: %s\n",WiFi.softAPIP().toString().c_str());}
static bool tryWifi(){String ssid=config.wifiSsid;ssid.trim();if(ssid.isEmpty()){Serial.println("WiFi STA: no SSID configured, skipping");return false;}Serial.printf("WiFi STA: connecting to '%s'\n",ssid.c_str());WiFi.mode(WIFI_AP_STA);WiFi.begin(config.wifiSsid.c_str(),config.wifiPass.c_str());uint32_t start=millis();while(WiFi.status()!=WL_CONNECTED&&millis()-start<20000){delay(500);Serial.print(".");}Serial.println();if(WiFi.status()==WL_CONNECTED){mode=LilygoNetworkMode::WIFI_CLIENT;Serial.printf("Network: WiFi %s\n",WiFi.localIP().toString().c_str());return true;}Serial.printf("WiFi STA failed status=%d\n",WiFi.status());return false;}
void setupLilygoNetwork(){startAp();if(tryWifi())return;if(lilygoGprsConnected()){mode=LilygoNetworkMode::LTE;Serial.println("Network: LTE");}else{mode=LilygoNetworkMode::AP_ONLY;Serial.println("Network: AP only");}}
void lilygoNetworkLoop(){if(millis()-lastCheckMs<5000)return;lastCheckMs=millis();if(WiFi.status()==WL_CONNECTED)mode=LilygoNetworkMode::WIFI_CLIENT;else if(lilygoGprsConnected())mode=LilygoNetworkMode::LTE;else mode=LilygoNetworkMode::AP_ONLY;} bool lilygoNetworkOnline(){return mode==LilygoNetworkMode::WIFI_CLIENT||mode==LilygoNetworkMode::LTE;} String lilygoNetworkModeName(){if(mode==LilygoNetworkMode::WIFI_CLIENT)return "WiFi";if(mode==LilygoNetworkMode::LTE)return "LTE";return "AP only";} String lilygoNetworkIp(){if(mode==LilygoNetworkMode::WIFI_CLIENT)return WiFi.localIP().toString();if(mode==LilygoNetworkMode::LTE)return "LTE";return WiFi.softAPIP().toString();} String lilygoNetworkStatusJson(){String json="{";json+="\"mode\":\""+lilygoNetworkModeName()+"\",";json+="\"online\":"+String(lilygoNetworkOnline()?"true":"false")+",";json+="\"ip\":\""+lilygoNetworkIp()+"\",";json+="\"wifiConnected\":"+String(WiFi.status()==WL_CONNECTED?"true":"false")+",";json+="\"wifiRssi\":"+String(WiFi.status()==WL_CONNECTED?WiFi.RSSI():0)+",";json+="\"lteConnected\":"+String(lilygoGprsConnected()?"true":"false")+",";json+="\"apSsid\":\""+apSsid+"\"";json+="}";return json;}
