#pragma once

#include <Arduino.h>

void c6NetworkSetup();
void c6NetworkLoop();
bool c6NetworkOnline();
bool c6NetworkTransportReady();
String c6NetworkIp();
int c6NetworkRssi();
String c6NetworkStatus();
String c6NetworkProfileName();
String c6NetworkStateName();
String c6NetworkReason();
bool c6NetworkHomeConfigured();
bool c6NetworkMobileConfigured();
bool c6NetworkApActive();
bool c6NetworkLinkWeak();
uint32_t c6NetworkWeakForMs();
uint32_t c6NetworkTransitionCount();
uint32_t c6NetworkLastTransitionAgeMs();
String c6NetworkBssid();
int c6NetworkChannel();
uint32_t c6NetworkDisconnectCount();
uint8_t c6NetworkLastDisconnectReason();
String c6NetworkLastDisconnectReasonName();
uint32_t c6NetworkLastDisconnectAgeMs();
bool c6NetworkLastDisconnectWasManagerInitiated();
String c6NetworkApSsid();
String c6NetworkApPassword();
void c6NetworkEnsureOnboardingAp();
